Repository CBNU-CMI/cbnu-alrimi, pull requests merged in 2020-11, with the labels that each got.

#46 [#45] refact: 다이어로그 파라미터 받기
  components/Dialog/ConfigDialog.js
  components/Dialog/NoticeDetailDialog.js
  components/Dialog/NoticeListDialog.js
  layout/Dialog.js
  styles/Dialog/dialog.scss
Labels: frontend, refactor

#48 [#47] feat: server api 분리
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  api/index.js
  components/Notice/NoticeDetail.js
  components/Notice/NoticeListBySiteId.js
  components/Restaurant/Menu.js
  components/Schedule/Academic.js
  package-lock.json
  package.json
  pages/index.js
  styles/Layout/global.scss
Labels: refactor

#50 [#49] feat: non-menu
  components/Restaurant/Menu.js
  components/Restaurant/Non-Menu.js
Labels: feature, frontend, markup

#51 [#35] bug: 지난달 주, 이후달 주 많이 나오는 오류 해결
  components/Schedule/getWeeks.js
Labels: bug-fix

#54 Feature/52 more page
  components/More/MoreList.js
  pages/more.js
  styles/More/more.scss
Labels: frontend, markup

#56 [#55] feat: modal창 제작, more page에서 click된 것 type 구분
  components/More/Modal.js
  components/More/MoreList.js
  pages/more.js
  styles/More/modal.scss
  styles/More/more.scss
Labels: frontend

#58 [#57] refact : 컴포넌트에 idx를 보내주는게 아닌 데이터를 보내주는 방식으로 변경
  components/More/Modal.js
  components/More/MoreList.js
Labels: refactor

#60 [#59] feat: 더보기 페이지 링크 연결
  components/More/Modal.js
  components/More/MoreList.js
Labels: feature

#63 [#62] bug: style 초기화
  pages/_app.js
  styles/index.js
Labels: bug-fix

#65 [#64] chore: border modify
  styles/More/more.scss
Labels: chore

#66 Update/53 main selector
  api/index.js
  components/Notice/NoticeListBySiteId.js
  components/Notice/Selector.js
  components/Notice/_Selector.js
  pages/index.js
  reducers/noticeSelect.js
  styles/Notice/notice.scss
Labels: frontend, update

#68 [#67] fix: divide notice list api
  api/index.js
  components/Dialog/ConfigDialog.js
  components/Dialog/NoticeListDialog.js
  components/Notice/NoticeListBySiteId.js
  components/Notice/Selector.js
  pages/index.js
  pages/notice.js
  public/flutter.js
  styles/Notice/notice.scss
Labels: bug-fix

#70 [#69] feat: alram config api
  api/index.js
  components/Dialog/ConfigDialog.js
  components/Dialog/list.js
Labels: api, feature, frontend

#72 [#71] update: config floating button
  components/Notice/FloatingButton.js
  components/Notice/NoticeList.js
  components/Notice/Selector.js
  pages/_app.js
  pages/index.js
  styles/Dialog/dialog.scss
  styles/Notice/notice.scss
Labels: frontend, style, update

#74 [#73] feature: alram allow, disallow
  api/index.js
  components/Dialog/ConfigDialog.js
  components/Dialog/list.js
  pages/index.js
  styles/Dialog/dialog.scss
Labels: feature, frontend

#76 [#29] feat: scrap
  api/index.js
  common/scrap.js
  components/Dialog/NoticeDetailDialog.js
  components/Notice/NoticeList.js
  components/Notice/NoticeListBySiteId.js
  components/Notice/Selector.js
  styles/Dialog/dialog.scss
  styles/Notice/notice.scss
Labels: api, feature, frontend, markup

#78 [#77] api: hybrid app
  components/Notice/NoticeList.js
  components/Notice/NoticeListBySiteId.js
  layout/main.js
  public/app.js
  public/flutter.js
Labels: api

#80 [#79] more page opensource, version note dialog
  components/Dialog/OpenSourceDialog.js
  components/Dialog/VersionNoteDialog.js
  components/Dialog/index.js
  components/More/MoreList.js
  pages/more.js
  styles/Dialog/OpenSourceDialog.scss
  styles/Dialog/VersionNoteDialog.scss
  styles/Dialog/dialog.scss
  styles/More/more.scss
Labels: feature, frontend, update

#82 Feature/81 ga
  Layout.js
  anayltics.js
  components/Notice/NoticeDetail.js
  components/Notice/NoticeList.js
  package-lock.json
  package.json
  pages/index.js
  pages/more.js
  pages/restaurant.js
  pages/schedule.js
Labels: feature

#84 [#83] app: open notice dialog from url
  components/Notice/NoticeList.js
Labels: app, feature

#86 [#85] api: token management
  api/index.js
  common/token.js
  pages/index.js
Labels: api

#88 [#87] feat: my alrim
  api/index.js
  components/Dialog/MyAlrimDialog.js
  components/Dialog/index.js
  components/More/MoreList.js
  styles/Dialog/MyAlrimDialog.scss
  styles/Dialog/dialog.scss
Labels: api, feature, frontend

#90 [#89] feat: register user
  api/index.js
  package.json
  pages/index.js
  pages/notice.js
Labels: api, feature, frontend

#92 [#91] feat: empty notice config
  components/Dialog/ConfigDialog.js
  components/Dialog/MyAlrimDialog.js
  components/Notice/Selector.js
  components/Uang/Empty.js
  components/Uang/index.js
  package.json
  pages/index.js
  public/img/off.png
  public/img/on.png
  public/img/uang_empty.png
  reducers/changeConfig.js
  reducers/index.js
  styles/Dialog/MyAlrimDialog.scss
  styles/Dialog/dialog.scss
  styles/Uang/uang.module.scss
  yarn.lock
Labels: feature, frontend

#94 [#93] feat: kepp selector state
  common/selector.js
  components/Notice/Selector.js
  components/Restaurant/Select.js
Labels: feature, frontend

#96 [#95] style: update style
  components/Dialog/NoticeDetailDialog.js
  components/Notice/NoticeDetail.js
  components/Restaurant/Non-Menu.js
  components/Uang/Eat.js
  components/Uang/index.js
  components/constants.js
  public/img/uang_eat.png
  styles/Dialog/dialog.scss
  styles/Notice/notice.scss
  styles/Schedule/academic.scss
  styles/Schedule/label.scss
  styles/Uang/uang.module.scss
Labels: frontend, style, update
