Repository CBNU-CMI/cbnu-alrimi, pull requests merged in 2020-10, with the labels that each got.

#22 [#19] chore: menu content에 key값 추가
  components/Restaurant/Menu.js
Labels: frontend

#25 스케쥴 페이지 마크업
  components/Layout/FakeFooter.js
  components/Restaurant/Day.js
  components/Restaurant/FakeFooter.js
  components/Restaurant/Menu.js
  components/Restaurant/Select.js
  components/Restaurant/Title.js
  components/Schedule/Academic.js
  components/Schedule/Calendar.js
  components/Schedule/Date.js
  components/Schedule/Label.js
  components/constants.js
  layout/main.js
  pages/restaurant.js
  pages/schedule.js
  reducers/index.js
  reducers/scheduleMonth.js
  styles/Layout/fakefooter.scss
  styles/Restaurant/menu.scss
  styles/Schedule/academic.scss
  styles/Schedule/calendar.scss
  styles/Schedule/date.scss
  styles/Schedule/label.scss
Labels: frontend, markup

#27 공지사항 타입 선택, 타입 선택시 해당하는 공지사항 불러오기
  common/dateForamt.js
  components/Notice/NoticeCard.js
  components/Notice/NoticeList.js
  components/Notice/Selector.js
  components/Notice/index.js
  pages/index.js
  reducers/index.js
  reducers/noticeSelect.js
  styles/Notice/notice.scss
Labels: feature, frontend

#30 캘린더 페이지 제작
  components/Schedule/Academic.js
  components/Schedule/Calendar.js
  components/Schedule/Date.js
  components/Schedule/division.js
  components/Schedule/getWeeks.js
  package-lock.json
  pages/schedule.js
  styles/Schedule/calendar.scss
  styles/Schedule/date.scss
Labels: frontend

#32 캘린더 페이지 달력 작업 완료
  components/Schedule/Calendar.js
  styles/Schedule/calendar.scss
Labels: frontend, markup

#33 [#31] feature: label timeline 데이터 연동
  components/Schedule/Academic.js
  components/Schedule/Label.js
  pages/schedule.js
Labels: frontend

#36 [#31] fix: 주소 변경, 년도 함께 보내기
  components/Schedule/Academic.js
Labels: frontend

#37 [#35] feature: 타임라인 시간 데이터 형식 변경
  common/dateFormat.js
  components/Schedule/Label.js
Labels: frontend

#38 Feature/28 infinite scroll
  components/Notice/NoticeCard.js
  pages/index.js
Labels: bug-fix, frontend

#42 Feature/41 notice list inifinite scroll
  components/Notice/NoticeDetail.js
  components/Notice/NoticeListBySiteId.js
  layout/Dialog.js
  pages/index.js
  styles/Dialog/dialog.scss
Labels: bug-fix, feature, frontend

#44 [#43] feat: notice-detail
  components/Dialog/NoticeDetailDialog.js
  components/Notice/NoticeDetail.js
  components/Notice/NoticeList.js
  components/Restaurant/Menu.js
  components/Schedule/Academic.js
  layout/Dialog.js
  styles/Dialog/dialog.scss
  styles/Layout/global.scss
  styles/Layout/reset.scss
  styles/Notice/notice.scss
Labels: feature, frontend
